include $(srctree)/ext/lib/Makefile
include $(srctree)/ext/hal/Makefile
include $(srctree)/ext/fs/Makefile
include $(srctree)/ext/debug/Makefile
ifdef CONFIG_MRAA
ZEPHYRINCLUDE += -I$(srctree)/ext/lib/mraa/include
endif
include $(srctree)/ext/lib/upm/Makefile
